Update abseil-cpp to LTS 20200923 Patch 3
https://github.com/abseil/abseil-cpp/releases/tag/20200923.3

This release contains `#include <limits>` which is no longer implicitly
included when building on newer versions of Ubuntu. This is
required for updating the docker images we use for RBE.

Without this, compilation fails with one of the following error
messages:

external/com_google_absl/absl/synchronization/internal/graphcycles.cc:451:26:
error: no member named 'numeric_limits' in namespace 'std'

Bug: 182172121
Test: n/a
Change-Id: I71d9aedbdd3cb1678cdcdad6d6124cd643a55a0d