Update jarjar ASM dependency to support JDK11 bytecode
Jarjar depends on ASM5 right now which does not handle
JDK11 bytecode and causes NoClassDefFoundError for
all inspectors.

Bug: 228861271
Fixes: 233902732
Test: Manual Test
Change-Id: Ib7359f6360243bdf6b2e50487a1c0e8426aeeed2