Add missing lsp4j.jsonrpc jars to lsp4ij dependencies
Include org.eclipse.lsp4j.jsonrpc and org.eclipse.lsp4j.jsonrpc.debug jars to the org.eclipse.lsp4j module library.
This fixes test failures due to NoClassDefFoundError for org.eclipse.lsp4j.jsonrpc.util.Preconditions.

Bug: 527183945, 527183372
Test: bazel test //tools/vendor/redhat-developer/lsp4ij:lsp4ij_tests__other
Change-Id: Ic80e2c2db1dba2d3ab068268022352d21f4916f6